;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        smex
        sp--self-insert-command
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        find-tag-regexp
        ido-find-file
        prelude-kill-whole-line
        ))
